### ISSUE TITLE
bluesky-live dependency missing

### ISSUE THREAD

**Issue by klauer** [conda-forge/databroker-feedstock#27]
Comparison recipe: 
https://github.com/nsls-ii-forge/databroker-feedstock/blob/master/recipe/meta.yaml

Issue:

Package installed from conda-forge missing dependency `bluesky-live`, which is not available on conda-forge. 

```
2021-02-22 15:32:46,297 - intake - ERROR - discovery.py:autodiscover:L147 - Error while loading entrypoint bluesky-event-stream
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/intake/source/discovery.py", line 250, in _load_entrypoint
    return entrypoint.load()
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/databroker/core.py", line 30, in <module>
    from bluesky_live.conversion import documents_to_xarray, documents_to_xarray_config
ModuleNotFoundError: No module named 'bluesky_live'
```

eventually leads to:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/intake/source/discovery.py", line 145, in autodiscover
    drivers[entrypoint.name] = _load_entrypoint(entrypoint)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/intake/source/discovery.py", line 252, in _load_entrypoint
    raise ConfigurationError(
intake.source.discovery.ConfigurationError: Failed to load bluesky-run driver because module databroker.core could not be found.
```

(full output: https://gist.github.com/klauer/f9b6a8b2869df85abe7368f4f6d12e4e)

Looks like it still _runs_ (assuming `~/.cache/scikit-image` is removed prior to running) but the amount of spam on import is overwhelming. 😕

**Comment by klauer** [comment]
Pending PR for dependency: https://github.com/conda-forge/staged-recipes/pull/14055
